spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: nh_user
    password: 1234
wap:
  aws:
    s3:
      cores:
        bucket: aws-kstars-file
        accessKey: AKIAXZCY2QYDC7ZLLXUW
        secretKey: 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