spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
wap:
  aws:
    s3:
      cores:
        bucket: aws-kstars-file
        accessKey: AKIAXZCY2QYDC7ZLLXUW
        secretKey: 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